{
    "name": "Grocery Shopping List",
    "summary": "Manage grocery shopping lists from website",
    "author": "Odoo Concept",
    "website": "https://odooconcept.com",
    "category": "Website",
    "version": "18.0.1.0.1",
    "depends": ["base", "website", "portal", "product"],
    "data": [
        "security/grocery_security.xml",
        "security/ir.model.access.csv",
        "views/grocery_list_line_views.xml",
        "views/grocery_list_views.xml",
        "views/grocery_product_views.xml",
        "views/grocery_store_views.xml",
        "views/menus.xml",
        "views/portal_templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "website_supermarket_list/static/src/components/store_autocomplete/store_autocomplete.xml",
            "website_supermarket_list/static/src/components/store_autocomplete/store_autocomplete.js",
            "website_supermarket_list/static/src/js/store_autocomplete_init.js",
            "website_supermarket_list/static/src/components/product_search/product_search.xml",
            "website_supermarket_list/static/src/components/product_search/product_search.js",
            "website_supermarket_list/static/src/components/grocery_list_progress/grocery_list_progress.xml",
            "website_supermarket_list/static/src/components/grocery_list_progress/grocery_list_progress.js",
            "website_supermarket_list/static/src/components/add_product_modal/add_product_modal.xml",
            "website_supermarket_list/static/src/components/add_product_modal/add_product_modal.js",
            "website_supermarket_list/static/src/components/store_autocomplete_component/store_autocomplete_component.xml",
            "website_supermarket_list/static/src/components/store_autocomplete_component/store_autocomplete_component.js",
            "website_supermarket_list/static/src/components/toggle_purchased/toggle_purchased.xml",
            "website_supermarket_list/static/src/components/toggle_purchased/toggle_purchased.js",
            "website_supermarket_list/static/src/components/complete_list_button/complete_list_button.xml",
            "website_supermarket_list/static/src/components/complete_list_button/complete_list_button.js",
            "website_supermarket_list/static/src/components/start_shopping_button/start_shopping_button.xml",
            "website_supermarket_list/static/src/components/start_shopping_button/start_shopping_button.js",
            "website_supermarket_list/static/src/components/add_product_button/add_product_button.xml",
            "website_supermarket_list/static/src/components/add_product_button/add_product_button.js",
            "website_supermarket_list/static/src/scss/grocery_list.scss",
        ],
    },
    "demo": [
        "demo/grocery_store_demo.xml",
        "demo/grocery_product_demo.xml",
        "demo/grocery_list_demo.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3",
}
